export const groupColors = {
    Green: "#66CC6A",
    Earthy: "#36A145",
    Alcohol: "red",
    "Fruit Like": "#66CC6A",
    Herbacious: "#B6ECBE",
    Citrus: "#F7FF33",
    "Dried Fruit": "",
    Savoury: "",
    Dairy: "",
    Sulphur: "#B6BEEC",
    Berry: "",
    "Tree Fruit": "",
    Tropical: "",
    Phenol: "",
    Chocolate: "#75561F",
    Meaty: "#936E2A",
    Nutty: "#C39237",
    Caramel: "#E49911",
    Pungent: "",
    Toasted: "",
    Roasted: "",
    Spice: "",
    Marine: "",
    Sour: "",
    Wood: "",
    Smoke: "",
    Petrol: "",
    Floral: "",
    Medicinal: "",
  };